AutoPartsShopAndForum/AutoPartsShopAndForum/Areas/Administrator/Controllers/SellersController.cs
namespace AutoPartsShopAndForum.Areas.Administrator.Controllers
{
    using AutoPartsShopAndForum.Infrastructure;
    using AutoPartsShopAndForum.Services.Web.User;
    using Microsoft.AspNetCore.Mvc;
    public class SellersController : BaseAdminController
    {
        private readonly IUserService userService;

        public SellersController(IUserService userService)
        {
            this.userService = userService;
        }

        public IActionResult Pending()
        {
            var pendingUsers = userService.GetPendingUsers();

            return View(pendingUsers);
        }

        [HttpPost]
        public IActionResult Pending(string id)
        {
            userService.ApproveSeller(this.User.GetId(), id);

            return Redirect(nameof(Pending));
        }
    }
}

AutoPartsShopAndForum/AutoPartsShopAndForum/Areas/Forum/Controllers/CategoriesController.cs
namespace AutoPartsShopAndForum.Areas.Forum.Controllers
{
    using AutoPartsShopAndForum.Services.Web.Forum;
    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : BaseForumController
    {
        private readonly ICategoriesService categoriesService;

        public CategoriesController(ICategoriesService categoriesService)
        {
            this.categoriesService = categoriesService;
        }

        public IActionResult All()
        {
            var categories = categoriesService.GetAll();

            return View(categories);
        }
    }
}

AutoPartsShopAndForum/AutoPartsShopAndForum/Controllers/ProductsController.cs
namespace AutoPartsShopAndForum.Controllers
{
    using AutoPartsShopAndForum.Models.View.Query.Products;
    using AutoPartsShopAndForum.Models.View.Query.SubCategory;
    using AutoPartsShopAndForum.Services.Web.Category;
    using AutoPartsShopAndForum.Services.Web.Product;
    using Microsoft.AspNetCore.Http.Extensions;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public class ProductsController : Controller
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;

        public ProductsController(IProductService productService, ICategoryService categoryService)
        {
            this.productService = productService;
            this.categoryService = categoryService;
        }

        public IActionResult All(ProductQueryViewModel queryModel)
        {
            int? categoryId = null;

            if (queryModel.CategoryId.HasValue)
            {
                categoryId = queryModel.CategoryId.Value;
            }

            var subCategories = new List<SubcategorySelectModel>();

            if (queryModel.SubCategories != null)
            {
                subCategories = queryModel.SubCategories.ToList();
            }
            else
            {
                subCategories = categoryService
                    .GetSubcategories(categoryId)
                    .Select(s => new SubcategorySelectModel()
                    {
                        Id = s.Id,
                        Name = s.Name,
                        Selected = false
                    }).ToList();
            }

            var selectedSubCategories = new List<int>();

            foreach (var subCat in subCategories)
            {
                if (subCat.Selected)
                {
                    selectedSubCategories.Add(subCat.Id);
                }
            }

            var products = productService.GetQueriedProducts(
                queryModel.CurrentPage,
                queryModel.ProductsPerPage,
                queryModel.SearchCriteria,
                queryModel.Sorting,
                queryModel.CategoryId,
                selectedSubCategories);

            var model = new ProductQueryViewModel()
            {
                CategoryId = categoryId,
                Products = products.Products,
                CurrentPage = queryModel.CurrentPage,
                ProductsPerPage = queryModel.ProductsPerPage,
                TotalProducts = products.TotalProducts,
                SubCategories = subCategories,
                SearchCriteria = String.Empty,
                Sorting = Services.Data.Product.ProductSorting.NoSorting,
                CurrentUrl = this.HttpContext.Request.GetEncodedUrl()
        };

            return View(model);
        }

        public IActionResult Details(ProductDetailsModel model)
        {
            string goBackUrl = Request.Headers["Referer"];

            if (!string.IsNullOrEmpty(model.LastUrl.Trim()))
            {
                goBackUrl = model.LastUrl;
            }

            model.LastUrl = goBackUrl;

            return View(model);
        }
    }
}

AutoPartsShopAndForum/AutoPartsShopAndForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoPartsShopAndForum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/catsummary.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/allpr.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/checkout.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoPartsShopAndForum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Catalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="All">All</a>
                        </li>
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
                        @if (this.User.IsAdmin() || this.User.IsSeller())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Seller" asp-controller="Products" asp-action="Add">Add Product</a>
                            </li>
                        }
                        else if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Candidate">Candidate for Seller</a>
                            </li>
                        }
                        @if (this.User.IsAdmin())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administrator" asp-controller="Sellers" asp-action="Pending">Seller Candidates</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Forum" asp-controller="Categories" asp-action="All">Forum</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/allpr.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>